画像アップロード機能
daichi-kusawake/touken-ec pull request #21
Opened 2024-02-06 14:09 UTC by daichi-kusawake

2024-02-26 05:33 UTC, daichi-kusawake commented
## レビュー後修正内容
- carrierwaveを用いた実装部分の削除
- activestorageでの複数画像ファイルアップロード機能実装


## 動作確認手順
activestorage用のバリデーションライブラリを追加したので以下のコマンド入力をお願いします
```
$ bundle install
```

db修正が必要な為、以下対応をお願いします
```
$ rake db:migrate:reset
$ rails db:seed
```

webで確認する場合は`rails s`でサーバー起動後、以下リンクアクセスをお願いします
http://127.0.0.1:3000/products

各画面へのリンクがページ内に入れておりませんので、確認する場合は各画面以下のリンクへアクセスをお願いします。

商品一覧：http://127.0.0.1:3000/products
商品登録：http://127.0.0.1:3000/products/new
商品詳細：http://127.0.0.1:3000/products/(id:1~n)
商品詳細：http://127.0.0.1:3000/products/(id:1~n)/edit


## 未対応箇所
- viewでのDB、cookieへのアクセスする箇所の修正
https://github.com/daichi-kusawake/touken-ec/pull/18#discussion_r1475493214
- 商品詳細ページのenumカラム表示が英語表記になっているものの修正
- ルーティングされていないメソッドのprivate宣言
https://github.com/daichi-kusawake/touken-ec/pull/18#discussion_r1482337728

2024-02-26 09:06 UTC, yuemori requested changes
upload処理の実装が怪しいんで、一回調べたり勉強してみた方が良さそうです

懸念点は直接話した通りなんで、

- RailsガイドのActiveStorageに書いてあるアップロード処理を一回やってみましょう
- トランザクションをちゃんと調べてやってみましょう
- なんか動かなかったりわかんなかったりして、自分で調べても解決できなさそうなら早めに聞いてくれていいですよ

って感じで進めてみてください

2024-02-26 09:06 UTC, yuemori commented on app/javascript/application.js
> +//import "preview"
必要ないものは外した方がいいですよ

2024-02-26 09:06 UTC, yuemori commented on app/views/layouts/_header.html.erb
> +          </button>-->
コメントアウトでコードを残すのは、例えばあとでコメントアウトを解除しなきゃいけないとかとか理由があったほうがいいですが、今回はどういう意図でしょう。
セットで[TODOコメント](https://qiita.com/taka-kawa/items/673716d77795c937d422)書いておくとより良いですね

ちなみに、HTMLはユーザが見ようと思ったら見える場所なのでコメントアウトしたものは見えちゃうのでサーバサイドのコードよりも気を配った方が良いです

2024-02-26 09:06 UTC, yuemori commented on app/controllers/products_controller.rb
>        redirect_to product_path(product.id)
redirect_toがここに書いてあるとproduct.updateが失敗した場合にredirect_toが呼ばれないのでリダイレクトが実行されないですね

2024-02-26 09:06 UTC, yuemori commented on app/views/products/edit.html.erb
> +    <% if @product.images.present? %>
product.images.eachは最初から空配列を返すのでここのif文は不要ですね

2024-02-26 09:06 UTC, yuemori commented on app/views/products/show.html.erb
> +    <% if @product.images.present? %>
ここも同上ですね

2024-02-26 09:06 UTC, yuemori commented on app/controllers/products_controller.rb
> +    #rails 6.0以降画像の更新が上書きできない問題の対処  https://github.com/rails/rails/issues/35817
good comment👍

2024-02-26 09:06 UTC, yuemori commented on app/controllers/products_controller.rb
> +        image  = product.images.find(image_id)
eachで回して `find(id)` するとimage_idsの回数だけSQLが発行されてしまいますね
これを一般的に[N+1問題](https://zenn.dev/gottsu/articles/914d45332450a3)と言います。

今の学習感だとまだちょっと難しいかもしれませんが、ちょっと調べてみるといいと思いますよ

2024-03-01 04:37 UTC, daichi-kusawake commented on app/views/layouts/_header.html.erb
> +          </button>-->
有難うございます。
見た目の変動確認するため記述したが、必要ないのでコメントアウトしておりました。
削除いたします！
TODO：他コメント使っていきます！

2024-03-01 04:37 UTC, daichi-kusawake commented on app/javascript/application.js
> +//import "preview"
ありがとうございます。
こちら不要なので削除いたしますm

2024-03-01 06:13 UTC, daichi-kusawake commented on app/controllers/products_controller.rb
>        redirect_to product_path(product.id)
もし更新成功の場：redirect_toで詳細画面
↓
if文の外にして詳細画面へリダイレクトするように修正しました。

2024-03-01 06:28 UTC, daichi-kusawake commented on app/views/products/edit.html.erb
> +    <% if @product.images.present? %>
product.images.eachのif文削除いたしました！

2024-03-01 06:55 UTC, daichi-kusawake commented on app/views/products/show.html.erb
> +    <% if @product.images.present? %>
こちらもproduct.images.eachのif文削除いたしました！

2024-03-04 09:05 UTC, yuemori commented on app/javascript/preview.js
> +document.addEventListener('DOMContentLoaded', () => {
惜しい。import消したならこっちも消していいんじゃないでしょうか

2024-03-04 09:05 UTC, yuemori commented on app/controllers/products_controller.rb
> +        image.purge #TODO
今直そうとしてると思うんでアドバイスって感じなんですけど、他の人とか、将来の自分が見たときに何をしなきゃいけないんだっけ、っていうのがわかるようにしておくといいですよ
（だいたい一ヶ月もしたら内容忘れちゃうんで一ヶ月後の自分は他人です）

```
TODO: purgeをXXXするのがYYYだからZZZにする
```

とか。あるいは `FIXME: purgeをループで呼んでるのは良くないけど直し方がわからないので一旦こうしている` とかでもいいですね

2024-03-05 07:01 UTC, daichi-kusawake commented on app/controllers/products_controller.rb
> +        image  = product.images.find(image_id)
ご指摘ありがとうございます！N+1問題の記事読みました！
アドバイスを頂き、今回はedit.html.erb側で受け取った:imagesから選択した削除予定の:delete_images配列を減算する形で、SQLを呼ばない形で対応しました。
（:delete_imagesがnilの場合に減算ができないため、ifで括っております）

selectが複数回呼び出されていることは今後、作成する上で気をつけていきます。

2024-03-05 07:13 UTC, daichi-kusawake commented on app/javascript/preview.js
> +document.addEventListener('DOMContentLoaded', () => {
忘れておりましたm
こちらimport消したので削除いたしました。

2024-03-05 07:15 UTC, daichi-kusawake commented on app/controllers/products_controller.rb
> +        image.purge #TODO
すぐ直すから一旦ぐらいの認識になっておりましたorz
理解の範囲でいつかのだれか（自分）に伝わるような記載で書きますm

2024-03-05 07:26 UTC, daichi-kusawake commented
レビュー後の内容を反映いたしましたm
お手すきの際にご確認頂けますと幸いです！

## ▽修正内容

- import previewとpreview.jsファイルの削除
- product.images.eachが空で返す為、edit.html.erbとshow.html.erbからif(空か判定)文を削除
- products_controller update内の変更
  - 削除対象をimages配列から削除する条件式に変更
  - update実行時の条件式からattachで追加する形式を削除

2024-03-06 08:19 UTC, yuemori approved these changes
LGTMです 👍 

細かいところ突っ込むとトランザクションの対応ではないですねｗ
あとは口頭で話したことはPRで何を話したとか、どういう対応をするとかは書いておくと他の人にも伝わっていいと思いますよ
追々でいいので頑張ってみてください 👍

2024-03-06 08:19 UTC, yuemori commented on app/controllers/products_controller.rb
> +    if params[:product][:delete_images]
あ、そうか。画像がないときにnilになるんですね。なるほど

2024-03-06 08:19 UTC, yuemori commented
activestorageの挙動は万人が知るところではないと思うんで、例えばcontrollerのところにこの前話したような内容を書いとくとかもありですね。
こういうのは調べたことの整理にもなりますし、ほかの人が調べる必要がなくなったり、挙動に変更があったときに当時の事情を推測できるようになったりします

```
def update
  # activerstorageはActionDispatch::Http::UploadedFileを渡すと新規ファイル、signed_idを渡すと既存ファイルのidと比較して存在するファイルの維持をする
  # また、update()の際に渡したsigned_idが存在しないものについては削除される
  # そのため、view側では新規ファイルをfile_field、既存ファイルをhiddien_fieldとして渡したうえで、
  # 削除するファイルについてはcheck_box_tagでdelete_imagesとして送信して新規ファイルの追加・既存ファイルの維持・削除対象ファイルをそれぞれ処理できるようにしている
  # see: https://railsguides.jp/active_storage_overview.html#%E6%B7%BB%E4%BB%98%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E7%BD%AE%E3%81%8D%E6%8F%9B%E3%81%88-vs-%E8%BF%BD%E5%8A%A0
```

みたいな。
これも追々でいいので、頭の片隅程度にでも。

2024-03-08 07:12 UTC, daichi-kusawake commented
なるほど、、
たしかに文章で残して置かないと、忘れてしまうもありました。
上記参考に次PRでコメント残しますｍ

2024-03-08 07:12 UTC, merged